default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
development:
  adapter: postgresql
  database: docker
  username: postgres
  password: 123456
  host: db
  port: 5432
  pool: 5
